# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Main build

on:
  push:
    branches: ["master"]

jobs:
  backend:
    defaults:
      run:
        working-directory: backend

    # strategy:
    #   matrix:
    #     os: ["linux", "darwin", "freebsd"]
    #     arch: ["amd64", "arm64"]

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"
          cache-dependency-path: backend/go.sum

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          workdir: backend
          distribution: goreleaser
          version: "~> v2"
          args: release --snapshot --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # - name: Upload assets
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: myapp
      #     path: myfolder/dist/*

      # - name: Download dependencies
      #   run: go mod download

      # - name: Build
      #   run: GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} go build -v -o frontporch_${{ matrix.os }}_${{ matrix.arch }} .
